version: '3.8'

services:

  # 1. SERVIÇO DO BANCO DE DADOS (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: financas_db
    # Mapeia a porta 5432 do container para a porta 5432 da sua máquina
    ports:
      - "5432:5432"
    # Monta um volume para que os dados persistam (não sejam apagados ao desligar o container)
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Variáveis de ambiente que o container do PostgreSQL usará
    environment:
      POSTGRES_USER: financas_user
      POSTGRES_PASSWORD: senha_secreta
      POSTGRES_DB: financas_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financas_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. SERVIÇO DO BACKEND (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financas_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.example 
    # ADICIONE ESTA SEÇÃO:
    environment:
      # Diz ao Passlib para usar uma sintaxe de hash mais robusta (2b) no teste interno
      PASSLIB_CONFIG: "bcrypt__ident=2b" 
    # FIM DA SEÇÃO ADICIONADA
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend      # O Dockerfile está dentro da pasta 'frontend'
      dockerfile: Dockerfile
    container_name: financas_frontend
    # Mapeia a porta 3000 do container para a porta 3000 da sua máquina
    ports:
      - "3000:3000"
    # Monta o volume para que as mudanças no código React sejam instantâneas (hot-reload)
    volumes:
      - ./frontend:/app
      - /app/node_modules # Impede que o host sobrescreva a pasta node_modules
    # Garante que o backend esteja rodando para o frontend fazer chamadas API
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: